version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
